version: '3.8'
services:
  nginx:
    image: nginx-proxy
    container_name: nginx-crm-proxy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    networks:
      - crm-network
    restart: always

networks:
  crm-network:
    driver: bridge