scrape_configs:
  - job_name: 'ds-crm'
    metrics_path: '/actuator/prometheus'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    scrape_interval: 15s
    static_configs:
      - targets: [ 'host.docker.internal:443' ]